name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: commit=$(git rev-parse --short HEAD)
      - run: pip install -r requirements.txt
      - run: pyinstaller --noconfirm --onedir --windowed --distpath './dist-$commit' --add-data './config:config/' './main.py'
      
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

