name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: echo "short_sha=`echo ${GITHUB_SHA::7}`" >> GITHUB_ENV 
      - run: pyinstaller --noconfirm --onedir --windowed --distpath "./dist-${GITHUB_SHA::7}" --add-data './config:config/' './main.py'
      - run: ls -l

      - name: Set output
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ steps.vars.outputs.short_sha }}
          path: dist-${{ steps.vars.outputs.short_sha }}/**
      - run: ls -l

